version: '3.8'

services:
  angular:
    image: nginx:alpine
    container_name: angular-app
    ports:
      - "4200:80"
    volumes:
      - ./appRentHub/dist/app-rent-hub/browser:/usr/share/nginx/html
      - ./appRentHub/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    image: openjdk:17
    container_name: springboot-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./RentHub/target/RentHub-0.0.1-SNAPSHOT.jar:/app.jar
    working_dir: /
    command: sh -c "echo 'Esperando 30 segundos...'; sleep 30; java -jar /app.jar"

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: bdRentHub
    ports:
      - "3307:3306"  # usa 3307 si ya tienes MySQL local en 3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:

